
sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: CONDA=true
    - os: linux
      python: '3.5'
      env: CONDA=true
    - os: linux
      python: '3.6'
      env: CONDA=true
    - os: linux
      python: '2.7'
      env: CONDA=false



before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi

install:
  - if [[ "${CONDA}" == "true" ]]; then
      PYTHON_VERSION="$TRAVIS_PYTHON_VERSION" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source auto_version/travis_install_conda.sh future numpy scipy  pip nose;
    fi
  - python setup.py install

script:
  - nosetests test_clifford.py

#after_success:
#  - coveralls
