# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: 'Test'
  strategy:
    matrix:
      linuxPython35:
        imageName: 'ubuntu-16.04'
        python.version: '3.5'
      linuxPython36:
        imageName: 'ubuntu-16.04'
        python.version: '3.6'
      linuxPython37:
        imageName: 'ubuntu-16.04'
        python.version: '3.7'
        
      macPython35:
        imageName: 'macos-10.13'
        python.version: '3.5'
      macPython36:
        imageName: 'macos-10.13'
        python.version: '3.6'
      macPython37:
        imageName: 'macos-10.13'
        python.version: '3.7'
        
      windowsPython35:
        imageName: 'vs2017-win2016'
        python.version: '3.5'
      windowsPython36:
        imageName: 'vs2017-win2016'
        python.version: '3.6'
      windowsPython37:
        imageName: 'vs2017-win2016'
        python.version: '3.7'
        
    maxParallel: 4
  
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install dependencies'
    
  - script: python setup.py install
    displayName: 'Install library'

  - script: |
      pip install nose
      pip install pytest
      pytest test --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: python setup.py sdist
    displayName: 'Build sdist'
