channels:
    - conda-forge
dependencies:
    - python=3.5
    - ipython
    - numpy
    - numba
    - scipy
    - matplotlib
    - nose
    - future
    - pandoc
    - nbconvert=4.2
    - ipykernel
    - nbsphinx
