channels:
    - conda-forge
dependencies:
    - python=3.7
    - ipython
    - numpy
    - numba=0.43
    - scipy
    - matplotlib
    - nose
    - future
    - pandoc
    - ipykernel
    - nbsphinx
    - nbconvert=5.4.1
