channels:
    - conda-forge
dependencies:
    - python=3.6
    - ipython
    - numpy
    - numba=0.43
    - scipy
    - matplotlib
    - nose
    - future
    - pandoc
    - nbconvert
    - ipykernel
    - nbsphinx
